INSERT INTO lab_monitors (cancer_type, workup_id, workup_frequency, workupType_id, workup_indication, workup_duration, workup_referral) VALUES (9, 4, '12 months', 1, 'routine', '24months', NULL);
INSERT INTO lab_monitors (cancer_type, workup_id, workup_frequency, workupType_id, workup_indication, workup_duration, workup_referral) VALUES (9, 5, '0', 1, 'high-risk', '0', NULL);
INSERT INTO lab_monitors (cancer_type, workup_id, workup_frequency, workupType_id, workup_indication, workup_duration, workup_referral) VALUES (9, 5, '0', 1, 'genetic mutation', '0', NULL);
INSERT INTO lab_monitors (cancer_type, workup_id, workup_frequency, workupType_id, workup_indication, workup_duration, workup_referral) VALUES (9, 6, '0', 1, 'aromatase inhibitor', '0', NULL);
INSERT INTO lab_monitors (cancer_type, workup_id, workup_frequency, workupType_id, workup_indication, workup_duration, workup_referral) VALUES (9, 7, '0', 1, 'post-treatment  trastuzumab', '0', NULL);
INSERT INTO lab_monitors (cancer_type, workup_id, workup_frequency, workupType_id, workup_indication, workup_duration, workup_referral) VALUES (9, 7, '0', 1, 'doxorubicin post-treatment', '0', NULL);
INSERT INTO lab_monitors (cancer_type, workup_id, workup_frequency, workupType_id, workup_indication, workup_duration, workup_referral) VALUES (5, 8, '6 months', 2, 'routine', '24months', NULL);
INSERT INTO lab_monitors (cancer_type, workup_id, workup_frequency, workupType_id, workup_indication, workup_duration, workup_referral) VALUES (5, 9, '6 months', 1, 'routine', '24months', NULL);
INSERT INTO lab_monitors (cancer_type, workup_id, workup_frequency, workupType_id, workup_indication, workup_duration, workup_referral) VALUES (5, 10, '6 months', 2, 'routine', '24months', NULL);
INSERT INTO lab_monitors (cancer_type, workup_id, workup_frequency, workupType_id, workup_indication, workup_duration, workup_referral) VALUES (5, 11, '6 months', 2, 'routine', '24months', NULL);
INSERT INTO lab_monitors (cancer_type, workup_id, workup_frequency, workupType_id, workup_indication, workup_duration, workup_referral) VALUES (5, 12, '12 months', 1, 'routine', '24months', NULL);
INSERT INTO lab_monitors (cancer_type, workup_id, workup_frequency, workupType_id, workup_indication, workup_duration, workup_referral) VALUES (5, 6, '0', 1, 'TSH suppression medication', '24months', NULL);
INSERT INTO lab_monitors (cancer_type, workup_id, workup_frequency, workupType_id, workup_indication, workup_duration, workup_referral) VALUES (5, 13, '0', 3, 'hyperthyroidism symptom', '0', NULL);
INSERT INTO lab_monitors (cancer_type, workup_id, workup_frequency, workupType_id, workup_indication, workup_duration, workup_referral) VALUES (13, 21, '6 months', 4, 'routine', '24 months', 'gastroenterologist');
INSERT INTO lab_monitors (cancer_type, workup_id, workup_frequency, workupType_id, workup_indication, workup_duration, workup_referral) VALUES (13, 14, '6 months', 1, 'routine', '24 months', NULL);
INSERT INTO lab_monitors (cancer_type, workup_id, workup_frequency, workupType_id, workup_indication, workup_duration, workup_referral) VALUES (13, 15, '6 months', 1, 'routine', '24 months', NULL);
INSERT INTO lab_monitors (cancer_type, workup_id, workup_frequency, workupType_id, workup_indication, workup_duration, workup_referral) VALUES (13, 23, '6 months', 5, 'routine', '24 months', 'nutritionist');
INSERT INTO lab_monitors (cancer_type, workup_id, workup_frequency, workupType_id, workup_indication, workup_duration, workup_referral) VALUES (13, 1, '6 months', 2, 'routine', '24 months', NULL);
INSERT INTO lab_monitors (cancer_type, workup_id, workup_frequency, workupType_id, workup_indication, workup_duration, workup_referral) VALUES (13, 2, '6 months', 2, 'routine', '24 months', NULL);
INSERT INTO lab_monitors (cancer_type, workup_id, workup_frequency, workupType_id, workup_indication, workup_duration, workup_referral) VALUES (13, 19, '6 months', 2, 'routine', '24 months', NULL);
INSERT INTO lab_monitors (cancer_type, workup_id, workup_frequency, workupType_id, workup_indication, workup_duration, workup_referral) VALUES (13, 20, '6 months', 2, 'routine', '24 months', NULL);
INSERT INTO lab_monitors (cancer_type, workup_id, workup_frequency, workupType_id, workup_indication, workup_duration, workup_referral) VALUES (16, 15, '6 months', 1, 'routine', '24 months', NULL);
INSERT INTO lab_monitors (cancer_type, workup_id, workup_frequency, workupType_id, workup_indication, workup_duration, workup_referral) VALUES (16, 1, '6 months', 2, 'routine', '24 months', NULL);
INSERT INTO lab_monitors (cancer_type, workup_id, workup_frequency, workupType_id, workup_indication, workup_duration, workup_referral) VALUES (16, 19, '6 months', 2, 'routine', '24 months', NULL);
INSERT INTO lab_monitors (cancer_type, workup_id, workup_frequency, workupType_id, workup_indication, workup_duration, workup_referral) VALUES (16, 20, '6 months', 2, 'routine', '24 months', NULL);
INSERT INTO lab_monitors (cancer_type, workup_id, workup_frequency, workupType_id, workup_indication, workup_duration, workup_referral) VALUES (16, 14, '6 months', 1, 'routine', '24 months', NULL);
INSERT INTO lab_monitors (cancer_type, workup_id, workup_frequency, workupType_id, workup_indication, workup_duration, workup_referral) VALUES (16, 15, '6 months', 1, 'routine', '24 months', NULL);
INSERT INTO lab_monitors (cancer_type, workup_id, workup_frequency, workupType_id, workup_indication, workup_duration, workup_referral) VALUES (16, 21, '6 months', 4, 'routine', '24 months', NULL);
INSERT INTO lab_monitors (cancer_type, workup_id, workup_frequency, workupType_id, workup_indication, workup_duration, workup_referral) VALUES (1, 15, '6 months', 1, 'routine', '24 months', NULL);
INSERT INTO lab_monitors (cancer_type, workup_id, workup_frequency, workupType_id, workup_indication, workup_duration, workup_referral) VALUES (1, 14, '6 months', 1, 'routine', '24 months', NULL);
INSERT INTO lab_monitors (cancer_type, workup_id, workup_frequency, workupType_id, workup_indication, workup_duration, workup_referral) VALUES (1, 17, '3 months', 2, 'routine', '24 months', NULL);
INSERT INTO lab_monitors (cancer_type, workup_id, workup_frequency, workupType_id, workup_indication, workup_duration, workup_referral) VALUES (1, 1, '6 months', 2, 'routine', '24 months', NULL);
INSERT INTO lab_monitors (cancer_type, workup_id, workup_frequency, workupType_id, workup_indication, workup_duration, workup_referral) VALUES (1, 19, '6 months', 2, 'routine', '24 months', NULL);
INSERT INTO lab_monitors (cancer_type, workup_id, workup_frequency, workupType_id, workup_indication, workup_duration, workup_referral) VALUES (1, 20, '6 months', 2, 'routine', '24 months', NULL);
INSERT INTO lab_monitors (cancer_type, workup_id, workup_frequency, workupType_id, workup_indication, workup_duration, workup_referral) VALUES (1, 22, '12 months', 4, 'routine', '24 months', 'gastroenterology');
