INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (23, 'no new local symptom', NULL, 1, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (23, 'no new systemic symptom', NULL, 2, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (23, 'good function in daily living', NULL, 3, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (23, 'no observed side effects', NULL, 4, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (9, 'breast pain', NULL, 1, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (9, 'arm swelling', NULL, 1, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (9, 'skin thickening', NULL, 1, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (9, 'breast mass', NULL, 1, NULL, 'yes');
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (9, 'nipple discharge', NULL, 1, NULL, 'yes');
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (24, 'bone pain', NULL, 2, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (24, 'fatigue', NULL, 2, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (24, 'weight loss', NULL, 2, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (24, 'shortness of breath', NULL, 2, NULL, 'yes');
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (24, 'persistent cough', NULL, 2, NULL, 'yes');
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (24, 'abdominal pain', NULL, 2, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (24, 'jaundice', NULL, 2, NULL, 'yes');
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (9, 'personality or behavioral change', NULL, 2, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (24, 'depression', NULL, 3, NULL, 'yes');
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (24, 'anxiety', NULL, 3, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (9, 'arms and legs numbness', NULL, 4, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (9, 'easy fatiguability', NULL, 4, NULL, 'yes');
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (5, 'neck mass', NULL, 1, NULL, 'yes');
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (5, 'hoarseness', NULL, 1, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (5, 'voice changes', NULL, 1, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (5, 'difficulty swallowing (dysphagia)', NULL, 1, NULL, 'yes');
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (5, 'Neck tightness', NULL, 1, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (5, 'cold intolerance', NULL, 4, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (5, 'constipation', NULL, 4, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (5, 'dry skin and hair', NULL, 4, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (5, 'memory or concentration issues', NULL, 4, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (5, 'heart palpitation', NULL, 4, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (5, 'tremors', NULL, 4, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (13, 'sensation food stuck after swallowing', NULL, 1, NULL, 'yes');
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (13, 'pain on swallowing', NULL, 1, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (13, 'regurgitation of food', NULL, 1, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (13, 'chest pain', NULL, 1, NULL, 'yes');
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (13, 'voice changes', NULL, 1, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (13, 'chronic cough', NULL, 1, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (13, 'frequent hiccups', NULL, 1, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (13, 'muscle weakness', NULL, 4, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (13, 'tingling of hands and feet', NULL, 4, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (13, 'balance problem in walking', NULL, 4, NULL, 'yes');
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (13, 'memory loss concentration problem', NULL, 4, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (13, 'shortness of breath', NULL, 4, NULL, 'yes');
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (13, 'recurrent lips ulcer', NULL, 4, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (13, 'sore tongue', NULL, 4, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (16, 'upper abdominal pain', NULL, 1, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (16, 'nausea', NULL, 1, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (16, 'vomiting after food intake', NULL, 1, NULL, 'yes');
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (16, 'early satiety', NULL, 1, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (16, 'heartburn', NULL, 1, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (16, 'difficulty swallowing', NULL, 1, NULL, 'yes');
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (16, 'black stools', NULL, 1, NULL, 'yes');
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (16, 'vomiting blood', NULL, 1, NULL, 'yes');
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (1, 'abdominal pain', NULL, 1, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (1, 'abdominal mass', NULL, 1, NULL, 'yes');
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (1, 'smaller caliber stool', NULL, 1, NULL, 'yes');
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (1, 'bloody stools', NULL, 1, NULL, 'yes');
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (1, 'incomplete bowel evacuation', NULL, 1, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (1, 'vomiting', NULL, 1, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (1, 'bloating', NULL, 1, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (1, 'severe constipation', NULL, 1, NULL, NULL);
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (1, 'abdominal enlargement', NULL, 1, NULL, 'yes');
INSERT INTO symptom_surveys (cancer_type, symptom_name, symptom_medicalTerm, symptom_category, symptom_filipino, symptom_alertable) VALUES (1, 'watery stools', NULL, 1, NULL, 'yes');
